### ISSUE TITLE
Failed to build microservices tutoriel

### ISSUE THREAD

**Issue by smaillns** [osgi/osgi.enroute#100]
Hi, 

Build fail when executing `~/microservice $ mvn -pl rest-app package`, the following error message is displayed 

> [ERROR] Failed to execute goal on project rest-app: Could not resolve dependencies for project org.osgi.enroute.examples.microservice:rest-app:jar:0.0.2-SNAPSHOT: The following artifacts could not be resolved: org.osgi.enroute.examples.microservice:dao-impl:jar:0.0.2-SNAPSHOT, org.osgi.enroute.examples.microservice:rest-service:jar:0.0.2-SNAPSHOT, org.osgi.enroute:osgi-api:pom:7.0.1-SNAPSHOT, org.osgi.enroute:impl-index:pom:7.0.1-SNAPSHOT, org.osgi.enroute:debug-bundles:pom:7.0.1-SNAPSHOT: Could not find artifact org.osgi.enroute.examples.microservice:dao-impl:jar:0.0.2-SNAPSHOT in OSGi (https://oss.sonatype.org/content/groups/osgi)

Any suggestions ! I'm a beginner with this framework .. I will be very grateful for your help, thanks

**Comment by smaillns** [comment]
@timothyjward may you help me

**Comment by timothyjward** [comment]
Closing as I believe this is now working.
