### ISSUE TITLE
Issue fetching ivy-latest.xml during gradle build

### ISSUE THREAD

**Issue by pd40** [osgi/osgi.enroute#2]
Just trying **gradle build** from the root project. It attempts to download an artifact that the **bndtools** project is not generating: 

	* Where:
	Settings file 'git/osgi.enroute/settings.gradle' line: 33

	* What went wrong:
	A problem occurred evaluating settings 'osgi.enroute'.
	> Could not resolve all dependencies for configuration 'classpath'.
	   > Could not resolve biz.aQute.bnd:biz.aQute.bnd.gradle:latest.
	     Required by:
	         unspecified:unspecified:unspecified
	      > Could not resolve biz.aQute.bnd:biz.aQute.bnd.gradle:latest.
	         > Could not get resource 'https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles/biz.aQute.bnd.gradle/ivy-latest.xml'.
	            > Could not GET 'https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles/biz.aQute.bnd.gradle/ivy-latest.xml'.
	               > peer not authenticated

**Comment by bjhargrave** [comment]
This is because you need network access to the bnd gradle plugin. Can you access that URL from the computer you are using to build? If your workstation cannot access that URL, you will need to get the bnd gradle plugin on the machine some other way and edit the gradle.properties file to point to where it is locally available.

**Comment by bjhargrave** [comment]
BTW, the issue is not that the ivy file does not exist. It is that your computer was not able to access the files on the cloudbees server.

**Comment by pd40** [comment]
Thanks. I was suspicious of the missing ivy file. I will try it from a different environment.
