### ISSUE TITLE
osgi.enroute.scheduler.simple.provider: /rest endpoint configuration shadowed by default servlet

### ISSUE THREAD

**Issue by sjka** [osgi/osgi.enroute#39]
The `RestControllerService` can be configured, e.g. to enable sending of CORS headers. However, when the configuration is added, then the previously registered `REST` servlets are not removed from the service registry, hence will stick around in the `HttpService` and will shadow any new one(s):

![image](https://user-images.githubusercontent.com/2592443/35361547-11679888-0162-11e8-9780-f412b2fa343b.png)

I can understand why the RestControllerService doesn't remove the REST services here:

https://github.com/osgi/osgi.enroute/blob/310c16182abab915907b40803aa8e3377d7ae8ed/osgi.enroute.rest.simple.provider/src/osgi/enroute/rest/simple/provider/RestControllerService.java#L105-L107

Nevertheless, if I'm not mistaken I think it would be required to remove them at least on deactivation here:

https://github.com/osgi/osgi.enroute/blob/310c16182abab915907b40803aa8e3377d7ae8ed/osgi.enroute.rest.simple.provider/src/osgi/enroute/rest/simple/provider/RestControllerService.java#L118-L121

Otherwise the new/updated configuration won't become effective as in the `HttpService` the first one wins. Also, with every configuration update a new `REST` service instance will be registered, piling up in the registry.

Did I miss anything? If you could just confirm my assumption, I'd be happy to create a PR of course.

**Comment by timothyjward** [comment]
Closing as this issue is no longer relevant.
