### ISSUE TITLE
OSGI EventAdmin 1.4 provider

### ISSUE THREAD

**Issue by cdelg** [osgi/osgi.enroute#64]
Maybe I missed something, but the API index provides the event package 1.4 whereas there is no providers for this version in the impl index.

**Comment by bjhargrave** [comment]
Eclipse Photon released to today including an EventAdmin implementation (which is the OSGi RI) which supports 1.4. Once this makes it to Maven Central, then the impl index can be updated to include it.

**Comment by cdelg** [comment]
Thank you for the information.

**Comment by timothyjward** [comment]
Keeping this open as a marker to update Event Admin when the new jar is released to Maven Central

**Comment by timothyjward** [comment]
This will be fixed in PR #67
