### ISSUE TITLE
Build Failure of app module

### ISSUE THREAD

**Issue by andreafino** [osgi/osgi.enroute#66]
Hi,

I have cloned repository, then I've launched command _mvn verify_. At the end, I have got an error on app module. 

**Error**

`Error   : Cannot find /error/org.apache.aries.javax.annotation-api;version=[0.0.1,0.0.2) Not found in [app [org.apache.felix.http.jetty,org.osgi.service.http.whiteboard,org.osgi.service.jaxrs,org.apache.commons.fileupload,ch.qos.logback.core,org.apache.commons.io,org.osgi.util.converter,tx-control-provider-jpa-xa,org.apache.felix.configurator,org.eclipse.equinox.event,org.osgi.service.event,org.apache.felix.log,org.apache.aries.javax.jax.rs-api,org.osgi.util.function,org.apache.felix.http.servlet-api,tx-control-provider-jdbc-xa,org.apache.felix.configadmin,org.osgi.service.log,org.osgi.enroute.examples.quickstart.rest,org.apache.felix.framework,org.eclipse.equinox.metatype,org.apache.servicemix.specs.annotation-api-1.3,org.apache.aries.jpa.container,org.apache.aries.jax.rs.whiteboard,tx-control-service-xa,slf4j.api,ch.qos.logback.classic,org.apache.felix.scr,org.osgi.util.promise,org.apache.aries.jpa.javax.persistence_2.1,org.apache.geronimo.specs.geronimo-osgi-locator,org.osgi.util.pushstream r/w=false], bnd-cache [C:/Users/afino/Desktop/AAA/osgi.enroute-master/examples/quickstart/app/target/tmp/export/app/cnf/cache/4.0.0/bnd-cache r/w=false], app [C:\Users\afino\Desktop\AAA\osgi.enroute-master\examples\quickstart\app\target\tmp\export\app\cnf\cache\4.0.0\app r/w=false]]
[ERROR] Error   : org.apache.aries.javax.annotation-api;version=[0.0.1,0.0.2) Not found in [app [org.apache.felix.http.jetty,org.osgi.service.http.whiteboard,org.osgi.service.jaxrs,org.apache.commons.fileupload,ch.qos.logback.core,org.apache.commons.io,org.osgi.util.converter,tx-control-provider-jpa-xa,org.apache.felix.configurator,org.eclipse.equinox.event,org.osgi.service.event,org.apache.felix.log,org.apache.aries.javax.jax.rs-api,org.osgi.util.function,org.apache.felix.http.servlet-api,tx-control-provider-jdbc-xa,org.apache.felix.configadmin,org.osgi.service.log,org.osgi.enroute.examples.quickstart.rest,org.apache.felix.framework,org.eclipse.equinox.metatype,org.apache.servicemix.specs.annotation-api-1.3,org.apache.aries.jpa.container,org.apache.aries.jax.rs.whiteboard,tx-control-service-xa,slf4j.api,ch.qos.logback.classic,org.apache.felix.scr,org.osgi.util.promise,org.apache.aries.jpa.javax.persistence_2.1,org.apache.geronimo.specs.geronimo-osgi-locator,org.osgi.util.pushstream r/w=false], bnd-cache [C:/Users/afino/Desktop/AAA/osgi.enroute-master/examples/quickstart/app/target/tmp/export/app/cnf/cache/4.0.0/bnd-cache r/w=false], app [C:\Users\afino\Desktop\AAA\osgi.enroute-master\examples\quickstart\app\target\tmp\export\app\cnf\cache\4.0.0\app r/w=false]]`

Anyone know how to solve it?
My java version is 1.8.0_171.

**Comment by timothyjward** [comment]
Apologies - this can happen when snapshots that the enRoute project builds against are deleted from remote dependency repositories. In this case there was a release of the Apache Aries JAX-RS Whiteboard over the weekend, and the related SNAPSHOTs have now expired because there are release versions available. I'll get going with a fix now and everything should be working again in a couple of hours.

**Comment by andreafino** [comment]
Very kind of you, thanks
