### ISSUE TITLE
Archetypes not available in Eclipse

### ISSUE THREAD

**Issue by alexweirig** [osgi/osgi.enroute#85]
Hello,

I wanted to start using the mvn archetypes for enRoute but I can't get Eclipse to find the archetypes.

It seems they are not visible in the archetypes catalogs.

I discovered the following link: 

https://oss.sonatype.org/content/groups/osgi/archetype-catalog.xml

that seems to contain the archetypes. I can browse and download the file and it looks OK but when I point Eclipse to the catalog it says the catalog is empty. When I point Eclipse to the locally downloaded catalog file it does indeed display the archetypes...

The documentation / examples pages on enRoute seem really nice, but there is no indication on how to get Eclipse find the archetypes.

(from the command shell it seems to work fine ... I've also pointed my Eclipse to my local maven installation which is the latest available: Apache Maven 3.5.4).

What am I missing?

Regards,

Alex

**Comment by timothyjward** [comment]
Hi Alex,

Documentation issues really should be raised against the https://github.com/osgi/osgi.enroute.site repository, as that's where the website is maintained. I've created a PR osgi/osgi.enroute.site#191 which would add a section on Eclipse Archetype setup. It would be good if you could verify that this works for you.

In addition I would like to warn you that Eclipse M2E has quite a few bugs in its archetype generation (failure to correctly rename files, failure to match package folder structures to package names) so please be careful when using Eclipse to run the archetypes.

**Comment by alexweirig** [comment]
Hi Tim, 

sorry for that, I thought I was doing something wrong with the archetypes. 

I remember you insisting on the m2e issues during your sessions at the EclipseCon. Since I’m amongst the people that don’t like maven, that’s not going to help 😉 but I want to give it try since I believe you did an amazing job on the new enRoute for r7. 

Thank you very much 

--- 

Mat frëndleche Gréiss,
Mit freundlichen Grüßen,
Meilleures salutations,
Kind regards, Alex Weirig Responsable Technique
Ville de Luxembourg
Service Enseignement
Centre Technolink Tel +352 4796 - 6127 Fax +352 42 88 81 Email alex.weirig@technolink.lu www.vdl.lu // www.technolink.lu Centre Technolink
2, rue Charles de Tornaco 
L-2623 LUXEMBOURG

**Comment by bjhargrave** [comment]
So we can close this issue then?

**Comment by alexweirig** [comment]
Hi BJ, 

sure, you can close the ticket. Tim opened the ticket for the website and it doesn’t seem to be a problem with the archetypes, although I don’t understand why I can’t add the archetype file using the server URL while I can add it when I download it, but I guess once the documentation is updated I’ll figure that out. 

Thanks 

--- 

Mat frëndleche Gréiss,
Mit freundlichen Grüßen,
Meilleures salutations,
Kind regards, Alex Weirig Responsable Technique
Ville de Luxembourg
Service Enseignement
Centre Technolink Tel +352 4796 - 6127 Fax +352 42 88 81 Email alex.weirig@technolink.lu www.vdl.lu // www.technolink.lu Centre Technolink
2, rue Charles de Tornaco 
L-2623 LUXEMBOURG
