### ISSUE TITLE
suffix is not taken into account while creating enroute projects in BndTools.

### ISSUE THREAD

**Issue by nport** [osgi/osgi.enroute#9]
BndTool enroute projects are created using a different template accoring to their name suffix. 
But, the suffix seems that is not taken into account if the project name is made of only two parts. 
In other words my.project.api  actually creates an project for api definition, whereas myproject.api creates a generic example project.

**Comment by tomq42** [comment]
Second this one.
Took me a good while to figure out why some of my projects got created in the expected fashion and some not.

**Comment by pkriens** [comment]
New templates no longer do name matching do to limitations in the new template system in bndtools
