### ISSUE TITLE
Recreating Quickstart Not Working

### ISSUE THREAD

**Issue by dmsilver2** [osgi/osgi.enroute#99]
I am going through the quickstart example on your site, but I am not able to complete it.

I first ran the below command and the quickstart was able to build succussfully

mvn org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate \
>     -DarchetypeGroupId=org.osgi.enroute.archetype \
>     -DarchetypeArtifactId=project \
>     -DarchetypeVersion=7.0.0
s\Daniel Silver\osgi\quickstart
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.168 s
[INFO] Finished at: 2019-02-22T14:38:38-05:00
[INFO] ------------------------------------------------------------------------

However, when I try to install the maven packages (mvn install) I get the following error.

[INFO] --- bnd-export-maven-plugin:4.1.0:export (default) @ app ---
[ERROR] Error   : The runbundles have changed. Failing the build!
Was: null
Is: \
        org.apache.felix.scr;version='[2.1.10,2.1.11)',\
        org.osgi.enroute.examples.quickstart.impl;version='[1.0.0,1.0.1)'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for quickstart 1.0-SNAPSHOT:
[INFO]
[INFO] quickstart ......................................... SUCCESS [  0.218 s]
[INFO] impl ............................................... SUCCESS [  1.707 s]
[INFO] app ................................................ FAILURE [  1.375 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.448 s
[INFO] Finished at: 2019-02-22T14:53:13-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:4.1.0:export (default) on project app: 1 errors found -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :app

**Comment by timothyjward** [comment]
It looks as if this is a user error, having missed the resolve step in the instructions https://enroute.osgi.org/tutorial/020-tutorial_qs.html#resolving-the-application

Please reopen if this is still an issue
